name: IssueOps Python Workflow

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug event payload
        run: echo "${{ toJson(github.event) }}"

      - name: Set issue number
        run: echo "NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Label new issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LABELS: triage

  run-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List directory structure
        run: ls -R

      - name: Print PYTHONPATH
        run: echo $PYTHONPATH

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest